# Generated by Django 5.0.7 on 2024-08-04 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='shared_pics')),
                ('title', models.CharField(blank=True, max_length=190)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('tag_one', models.CharField(blank=True, max_length=50)),
                ('tag_two', models.CharField(blank=True, max_length=50)),
                ('era', models.CharField(blank=True, max_length=20)),
                ('when_added', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Pictures',
                'ordering': ['when_added'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='glasgow_now_and_then_app.picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glasgow_now_and_then_app.userprofile')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
