# Generated by Django 5.0.7 on 2024-08-04 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasgow_now_and_then_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['when_added']},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment_body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_on',
            new_name='when_added',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='tag_one',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='tag_two',
        ),
        migrations.AddField(
            model_name='picture',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='era',
            field=models.CharField(choices=[('Present_day', 'Present Day'), ('2010-2020', '2010-2020'), ('2000-2010', '2000-2010'), ('1990s', '1990s'), ('1980s', '1980s'), ('1970s', '1970s'), ('1960s and earlier', '1960s and earlier')], max_length=100),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='shared_pics'),
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_label', models.CharField(blank=True, max_length=50)),
                ('when_added', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_tags', to='glasgow_now_and_then_app.picture')),
            ],
            options={
                'verbose_name_plural': 'Image Tags',
                'ordering': ['when_added'],
            },
        ),
        migrations.CreateModel(
            name='PictureLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_likes', to='glasgow_now_and_then_app.picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'image')},
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
