# Generated by Django 5.0.7 on 2024-08-05 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasgow_now_and_then_app', '0002_alter_comment_user_alter_comment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='era',
            field=models.CharField(choices=[('present_day', 'Present Day'), ('2010-2020', '2010-2020'), ('2000-2010', '2000-2010'), ('1990s', '1990s'), ('1980s', '1980s'), ('1970s', '1970s'), ('1960s_and_earlier', '1960s and earlier')], max_length=100),
        ),
        migrations.AlterField(
            model_name='picture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
